# Generated by Django 5.2.7 on 2025-10-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_method_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('PROCESSING', 'En Proceso'), ('SHIPPED', 'Enviada'), ('DELIVERED', 'Entregada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
    ]
