# Generated by Django 5.2.7 on 2025-10-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_order_total_alter_orderdetails_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('personas', 'Servicio de Personas'), ('inventario', 'Servicio de Inventario'), ('analytics', 'Servicio de Analytics'), ('auth', 'Servicio de Autenticación')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Saludable'), ('degraded', 'Degradado'), ('unhealthy', 'No disponible'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('response_time_ms', models.IntegerField(default=0, help_text='Tiempo de respuesta en milisegundos')),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la verificación falló', null=True)),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Número de verificaciones fallidas consecutivas')),
            ],
            options={
                'ordering': ['-last_check'],
                'unique_together': {('service_name',)},
            },
        ),
    ]
