# Generated by Django 5.2.7 on 2025-11-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_order_confirmed_at_order_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default='', help_text='Email del cliente (cache)', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Nombre completo del cliente (cache)', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', help_text='Teléfono del cliente (cache)', max_length=20),
        ),
    ]
