# Generated by Django 5.2.7 on 2025-10-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.category')),
            ],
            options={
                'verbose_name': 'Drill',
                'verbose_name_plural': 'Drills',
            },
        ),
        migrations.CreateModel(
            name='DrillPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.drill')),
            ],
            options={
                'verbose_name': 'Drill Price History',
                'verbose_name_plural': 'Drill Price Histories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.drill')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('event_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventory')),
            ],
            options={
                'verbose_name': 'Inventory Event',
                'verbose_name_plural': 'Inventory Events',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.warehouse'),
        ),
    ]
