# Generated by Django 4.2.7 on 2025-10-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_product_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
