# Generated by Django 5.2.7 on 2025-10-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_product_price_alter_productpricehistory_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Proveedor')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, default='Chile', max_length=100, null=True, verbose_name='País')),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True, verbose_name='Términos de Pago')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RUT/Tax ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio de Costo (CLP)'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.IntegerField(default=10, verbose_name='Cantidad de Reorden'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('DISCONTINUED', 'Descontinuado')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio de Venta (CLP)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(default='UND', max_length=10, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventario.supplier', verbose_name='Proveedor'),
        ),
    ]
