# Generated by Django 5.2.7 on 2025-10-26 02:45

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_supplier_alter_product_options_product_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('ordered', 'Ordenada'), ('received', 'Recibida'), ('cancelled', 'Cancelada')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorders', to='inventario.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorders', to='inventario.supplier')),
            ],
            options={
                'verbose_name': 'Reorder Request',
                'verbose_name_plural': 'Reorder Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
