# Generated by Django 5.2.7 on 2025-10-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_reorderrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inventario.reorderrequest')),
            ],
            options={
                'verbose_name': 'Reorder Status History',
                'verbose_name_plural': 'Reorder Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
