# Generated by Django 5.2.7 on 2025-10-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_reorderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='on_time_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa entregas a tiempo (0-1)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificación (0-5)'),
        ),
    ]
