# Generated by Django 5.2.7 on 2025-11-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auditlog_productcosthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('order_reference', models.CharField(blank=True, help_text='ID/UUID de la orden externa en servicio_ventas', max_length=64, null=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha/hora en que la reserva expira si no se confirma')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventario__model_97c594_idx',
            old_name='inventario_model_ac_1bdb31_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventario__created_3709a6_idx',
            old_name='inventario_created__aaf03e_idx',
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventario.product'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['product', 'status'], name='inventario__product_62f332_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at'], name='inventario__expires_7c282e_idx'),
        ),
    ]
