"""
Django settings for servicio_ventas project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()  # Carga las variables de entorno desde el archivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# IMPORTANTE: Debe ser la misma SECRET_KEY que el servicio de autenticación
SECRET_KEY = os.getenv('SECRET_KEY') or os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY or DJANGO_SECRET_KEY environment variable must be set in production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    # Health Check
    'health_check',
    'health_check.db',
    'health_check.storage',
    'health_check.contrib.migrations',
    'ventas.apps.VentasConfig',  # Cambiado para que registre los signals correctamente
    'corsheaders',
]

REST_FRAMEWORK = {
    # Deshabilitado para desarrollo - sin autenticación requerida
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework_simplejwt.authentication.JWTAuthentication',
    # ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Permitir todo para desarrollo
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'servicio_ventas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'servicio_ventas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {}

# Soporte para DATABASE_URL (p. ej., postgres://user:pass@host:5432/db)
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    try:
        import dj_database_url  # type: ignore
        DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    except Exception:
        # Fallback a variables separadas si no está instalado o falla el parseo
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DATABASE_DB'),
            'USER': os.getenv('DATABASE_USER'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD'),
            'HOST': os.getenv('DATABASE_SERVER'),
            'PORT': os.getenv('DATABASE_PORT'),
        }
else:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_DB'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_SERVER'),
        'PORT': os.getenv('DATABASE_PORT'),
    }

# -----------------------------------------------------------
# Secondary (analytics) database scaffold
# If ANALYTICS_DATABASE_DB is not provided, mirror default for now.
# This allows introducing a second physical database later without code churn.
# -----------------------------------------------------------
SECONDARY_DB_NAME = os.getenv('ANALYTICS_DATABASE_DB')
if SECONDARY_DB_NAME:
    DATABASES['analytics'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': SECONDARY_DB_NAME,
        'USER': os.getenv('ANALYTICS_DATABASE_USER', os.getenv('DATABASE_USER')),
        'PASSWORD': os.getenv('ANALYTICS_DATABASE_PASSWORD', os.getenv('DATABASE_PASSWORD')),
        'HOST': os.getenv('ANALYTICS_DATABASE_SERVER', os.getenv('DATABASE_SERVER')),
        'PORT': os.getenv('ANALYTICS_DATABASE_PORT', os.getenv('DATABASE_PORT')),
    }
else:
    # Mirror default connection (logical separation only at this stage)
    DATABASES['analytics'] = DATABASES['default'].copy()

# Register DB router (scaffold). Future analytics/reporting app labels will be routed.
DATABASE_ROUTERS = ['servicio_ventas.dbrouters.ServiceRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Para el uso del Frontend en desarrollo
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite development server
    "http://127.0.0.1:5173",
    "http://localhost",
    "http://localhost:80",
]

# Permitir cookies en solicitudes CORS
CORS_ALLOW_CREDENTIALS = True

# Para desarrollo, NO permitir todos los orígenes si CORS_ALLOW_CREDENTIALS es True
CORS_ALLOW_ALL_ORIGINS = False

# Configuración adicional para desarrollo
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']

# Configurar JWT para session backend
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,  # No usamos blacklist en microservicios secundarios
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,  # DEBE SER LA MISMA QUE EN servicio_auth
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Rep Drill - API de Ventas',
    'DESCRIPTION': 'API RESTful para gestión de ventas, órdenes, envíos y pagos. '
                   'Permite crear y gestionar todo el flujo de ventas y seguimiento.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api',
    'SECURITY': [{'bearerAuth': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
}

# ===========================================
# CONFIGURACIÓN DE MICROSERVICIOS
# ===========================================

# URL del servicio de inventario
INVENTARIO_SERVICE_URL = os.getenv('INVENTARIO_SERVICE_URL', 'http://inventario:8000')

# URL del servicio de personas
PERSONAS_SERVICE_URL = os.getenv('PERSONAS_SERVICE_URL', 'http://personas:8000')

# Timeout para requests entre servicios (en segundos)
MICROSERVICE_REQUEST_TIMEOUT = 5

# ===========================================
# CONFIGURACIÓN DE LOGGING
# ===========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'ventas.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'ventas': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# ============================================
# Configuración de Celery
# ============================================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Santiago'
CELERY_ENABLE_UTC = False
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos


