# Generated by Django 5.2.7 on 2025-10-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('users', 'Usuarios'), ('customers', 'Clientes'), ('employees', 'Empleados'), ('products', 'Productos'), ('inventory', 'Inventario'), ('sales', 'Ventas'), ('reports', 'Reportes')], max_length=20, verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado')], max_length=20, unique=True, verbose_name='Nombre del rol'),
        ),
    ]
