# Generated by Django 5.2.7 on 2025-10-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_order_id_order_customer_id_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='method',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Preparación', 'En Preparación'), ('Enviado', 'Enviado'), ('En Tránsito', 'En Tránsito'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Devuelto', 'Devuelto')], default='Pendiente', max_length=50),
        ),
    ]
