# Generated by Django 5.2.7 on 2025-10-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_updated',
            field=models.BooleanField(default=False),
        ),
    ]
