# Generated by Django 4.2.7 on 2025-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_forecastaccuracyhistory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productdemandmetrics',
            name='analytics_p_average_c45934_idx',
        ),
        migrations.RemoveIndex(
            model_name='productdemandmetrics',
            name='analytics_p_trend_cbf52b_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockreorderrecommendation',
            name='analytics_s_product_8cd6be_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockreorderrecommendation',
            name='analytics_s_status_298b42_idx',
        ),
        migrations.RenameIndex(
            model_name='forecastaccuracyhistory',
            new_name='analytics_f_forecas_439ebe_idx',
            old_name='analytics_f_forecas_idx',
        ),
        migrations.RenameIndex(
            model_name='forecastaccuracyhistory',
            new_name='analytics_f_product_cff0c7_idx',
            old_name='analytics_f_product_idx',
        ),
        migrations.RenameIndex(
            model_name='forecastaccuracyhistory',
            new_name='analytics_f_forecas_9ad53e_idx',
            old_name='analytics_f_horizon_idx',
        ),
        migrations.RenameIndex(
            model_name='forecastaccuracyhistory',
            new_name='analytics_f_created_7d4203_idx',
            old_name='analytics_f_created_idx',
        ),
        migrations.RenameIndex(
            model_name='productdemandmetrics',
            new_name='idx_product_period',
            old_name='analytics_p_product_675e82_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreorderrecommendation',
            new_name='idx_priority_created',
            old_name='analytics_s_reorder_b7cc0d_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreorderrecommendation',
            new_name='idx_stockout_date',
            old_name='analytics_s_stockou_62f7d2_idx',
        ),
        migrations.AddIndex(
            model_name='productdemandmetrics',
            index=models.Index(fields=['-average_daily_demand', 'product_id'], name='idx_demand_product'),
        ),
        migrations.AddIndex(
            model_name='productdemandmetrics',
            index=models.Index(fields=['period_start', 'period_end'], name='idx_period_range'),
        ),
        migrations.AddIndex(
            model_name='productdemandmetrics',
            index=models.Index(fields=['trend', '-calculated_at'], name='idx_trend_calc'),
        ),
        migrations.AddIndex(
            model_name='productdemandmetrics',
            index=models.Index(fields=['-calculated_at'], name='idx_calc_time'),
        ),
        migrations.AddIndex(
            model_name='stockreorderrecommendation',
            index=models.Index(fields=['product_id', 'warehouse_id', '-created_at'], name='idx_prod_wh_created'),
        ),
        migrations.AddIndex(
            model_name='stockreorderrecommendation',
            index=models.Index(fields=['status', '-created_at'], name='idx_status_created'),
        ),
        migrations.AddIndex(
            model_name='stockreorderrecommendation',
            index=models.Index(fields=['-created_at'], name='idx_created_at'),
        ),
        migrations.AddConstraint(
            model_name='stockreorderrecommendation',
            constraint=models.UniqueConstraint(fields=('product_id', 'warehouse_id', 'created_at'), name='unique_recommendation_per_day'),
        ),
    ]
