# Generated by Django 4.2.7 on 2025-11-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_productdemandmetrics_analytics_p_average_c45934_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=100)),
                ('task_name', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(db_index=True, default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_task_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_name', '-started_at'], name='analytics_t_task_na_f51d25_idx'), models.Index(fields=['status', '-started_at'], name='analytics_t_status_80bda5_idx')],
            },
        ),
    ]
