# Generated by Django 4.2.7 on 2025-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_taskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCategoryAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(db_index=True)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('products_count', models.IntegerField(default=0)),
                ('mape', models.DecimalField(decimal_places=2, help_text='Mean Absolute Percentage Error %', max_digits=8)),
                ('mae', models.DecimalField(decimal_places=2, default=0, help_text='Mean Absolute Error promedio', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precisión Forecast Categoría',
                'verbose_name_plural': 'Precisiones Forecast Categoría',
                'db_table': 'analytics_forecast_category_accuracy',
                'ordering': ['-window_end', 'category_id'],
            },
        ),
        migrations.CreateModel(
            name='ForecastProductAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('days_evaluated', models.IntegerField(default=0)),
                ('mape', models.DecimalField(decimal_places=2, help_text='Mean Absolute Percentage Error %', max_digits=8)),
                ('mae', models.DecimalField(decimal_places=2, default=0, help_text='Mean Absolute Error', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precisión Forecast Producto',
                'verbose_name_plural': 'Precisiones Forecast Producto',
                'db_table': 'analytics_forecast_product_accuracy',
                'ordering': ['-window_end', 'product_id'],
                'indexes': [models.Index(fields=['product_id', '-window_end'], name='analytics_f_product_c1e7d2_idx'), models.Index(fields=['-created_at'], name='analytics_f_created_764557_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='forecastproductaccuracy',
            constraint=models.UniqueConstraint(fields=('product_id', 'window_start', 'window_end'), name='uniq_product_window_accuracy'),
        ),
        migrations.AddIndex(
            model_name='forecastcategoryaccuracy',
            index=models.Index(fields=['category_id', '-window_end'], name='analytics_f_categor_e16745_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastcategoryaccuracy',
            index=models.Index(fields=['-created_at'], name='analytics_f_created_f403ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastcategoryaccuracy',
            constraint=models.UniqueConstraint(fields=('category_id', 'window_start', 'window_end'), name='uniq_category_window_accuracy'),
        ),
    ]
