name: Docker Build

# Este workflow es opcional y solo se ejecuta manualmente o en tags
on:
  workflow_dispatch:  # Permite ejecución manual
  push:
    tags:
      - 'v*'  # Se ejecuta en tags como v1.0.0

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [auth, personas, inventario, ventas]
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/servicio_${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/servicio_${{ matrix.service }}
          push: false  # Cambiar a true si quieres push automático
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker image
        run: |
          docker run --rm ${{ steps.meta.outputs.tags }} python --version
          echo "Image built successfully!"
